Repository DEFRA/defra-ruby-alert, pull requests merged in 2020-06, with the labels that each got.

#9 Remove airbrake close hook from gem
  .ruby-version
  lib/defra_ruby/alert/airbrake_runner.rb
  spec/defra_ruby/alert/airbrake_runner_spec.rb
Labels: bug

#8 Update airbrake version to be compatible with latest rails and ruby
  .ruby-version
  .travis.yml
  defra_ruby_alert.gemspec
  lib/defra_ruby/alert/airbrake_runner.rb
  spec/defra_ruby/alert/airbrake_runner_spec.rb
Labels: enhancement

#10 Rename blacklist to blocklist
  README.md
  lib/defra_ruby/alert/airbrake_runner.rb
  lib/defra_ruby/alert/configuration.rb
  spec/defra_ruby/alert/airbrake_runner_spec.rb
  spec/defra_ruby/alert/configuration_spec.rb
Labels: housekeeping
